apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: loadtest
spec:
  metrics:
  - name: loadtest-vote
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: siege
                image: prabhatsingh014/hello-there:v6
                command:
                  - siege
                  - "--concurrent=2"
                  - "--benchmark"
                  - "--time=5m"
                  - "--header='X-Canary: siege'"
                  - "http://hello.example.com/hello"
              restartPolicy: Never
              hostAliases:
              - ip: "127.0.0.1"
                hostnames:
                - "hello.example.com"
          backoffLimit: 4
