{{- if .Values.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hello-there.roleBinding" . }}
  labels:
    {{- include "hello-there.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "hello-there.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "hello-there.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
