{{- if .Values.roleName.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hello-there.roleName" . }}
  labels:
    {{- include "hello-there.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
