apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hello-there.fullname" . }}
  labels:
    {{- include "hello-there.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hello-there.selectorLabels" . | nindent 6 }}
  strategy:
    blueGreen: null
    canary:
      canaryService: {{ include "hello-there.fullname" . }}-preview
      stableService: {{ include "hello-there.fullname" . }}
      steps:
      - setCanaryScale:
          replicas: 2
      - experiment:
          duration: 3m
          templates:
          - name: canary
            specRef: canary
            service:
              name: experiment
          analyses:
            - name: fitness-test
              templateName: canary-fitness-test
      - setWeight: 20
      - pause:
          duration: 10s
      - setWeight: 40
      - pause:
          duration: 10s
      - setWeight: 60
      - analysis:
          templates:
          - templateName: loadtest
          - templateName: latency
      - setWeight: 80
      - pause:
          duration: 10s
      - setWeight: 100
      trafficRouting:
        nginx:
          stableIngress: {{ include "hello-there.fullname" . }}
          additionalIngressAnnotations:
            canary-by-header: X-Canary
            canary-by-header-value: siege
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hello-there.fullname" . }}
    scaleDown: onsuccess
