apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-there.fullname" . }}-preview
  labels:
    {{- include "hello-there.labels" . | nindent 4 }}
spec:
  type: {{ .Values.servicePreview.type }}
  ports:
    - port: {{ .Values.servicePreview.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-there.selectorLabels" . | nindent 4 }}
